In [ ]:
import pandas as pd
xls = pd.ExcelFile('../data_raw/adj9285_Data_file_S1.xlsx')


In [2]:
import numpy as np
def excel_to_df (df1,tests_indices,patients_cols,patients_infected,len_list,diff_col = 2):
    all_data_df = pd.DataFrame(columns = ['patient.number','infected.yn','type.sample','test','value','dpi'])
    for test_index in tests_indices:
        test_indices = np.arange(test_index,test_index+len_list)
        if test_index+len_list>len(df1):
            test_indices = np.arange(test_index,len(df1))
        for col_num in patients_cols:
            for ind in test_indices:
                if col_num<=patients_infected:
                    infected_yn = 'y'
                else:
                    infected_yn='n'
                row_dict = {'patient.number':[col_num-diff_col],
                            'infected.yn':[infected_yn],
                            'type.sample':df1.loc[0][0],
                            'test':[df1.loc[test_index][0]],
                            'value':[df1.loc[ind][col_num]],
                            'dpi':[df1.loc[ind][0]]
                            }
                all_data_df = pd.concat([all_data_df,pd.DataFrame(row_dict)],ignore_index=True)
    all_data_df = all_data_df.dropna()
    return all_data_df

In [3]:
df1 = pd.read_excel(xls, 'Fig2a',header=None)
tests_indices = [1,21,41,61,81,101,121,141]
len_list = 19
patient_cols = np.arange(3,36)
all_data_df = excel_to_df(df1,tests_indices,patient_cols,19,len_list)
print(len(all_data_df))
print(all_data_df['dpi'].unique())

4472
[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28]


In [4]:
df1 = pd.read_excel(xls, 'Fig2a',header=None)
print(df1.to_string())

          0     1            2            3            4            5            6            7            8            9            10           11           12           13           14           15           16            17           18           19           20          21          22           23           24           25           26           27           28            29           30           31           32           33           34           35  36                              37                38                39
0      NASAL   NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN           NaN          NaN          NaN          NaN         NaN         NaN          NaN          NaN          NaN          NaN          NaN          NaN           NaN          NaN          NaN          NaN          NaN          NaN          NaN NaN   

In [5]:
df2 = pd.read_excel(xls, 'Fig 2b',header=None)
tests_indices = [1,20,39,58,77,96,115,134,153,172]
df_ret_2 = excel_to_df(df2,tests_indices,np.arange(1,35),19,18,diff_col=0)
all_data_df = pd.concat([all_data_df,df_ret_2])
print(len(all_data_df))
print(all_data_df['dpi'].unique())

9906
[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28]


In [6]:
df2 = pd.read_excel(xls, 'Fig 2b',header=None)
print(df2.to_string())

          0           1            2            3           4            5            6            7           8            9            10           11          12           13           14          15           16           17          18          19          20          21          22          23          24          25          26          27          28          29          30          31           32          33          34  35                              36                37                38
0     PLASMA         NaN          NaN          NaN         NaN          NaN          NaN          NaN         NaN          NaN          NaN          NaN         NaN          NaN          NaN         NaN          NaN          NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          NaN         NaN         NaN NaN                             NaN               NaN       

In [7]:
df3 = pd.read_excel(xls, 'Fig 5a',header=None)
tests_indices = [1,22,43]
df_ret_3 = excel_to_df(df3,tests_indices,np.arange(1,35),19,20,diff_col=0)
all_data_df = pd.concat([all_data_df,df_ret_3])
print(len(all_data_df))
print(all_data_df['dpi'].unique())


11664
[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28 90]


In [8]:
df3 = pd.read_excel(xls, 'Fig 5a',header=None)
print(df3.to_string())

       0           1            2           3            4           5           6           7            8            9           10           11          12          13            14          15           16           17           18          19         20         21         22         23         24         25          26         27          28         29         30         31         32         33          34  35                      36                37                38
0   Nasal         NaN          NaN         NaN          NaN         NaN         NaN         NaN          NaN          NaN         NaN          NaN         NaN         NaN           NaN         NaN          NaN          NaN          NaN         NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN        NaN         NaN        NaN        NaN        NaN        NaN        NaN         NaN NaN                     NaN               NaN               NaN
1     IgG         NaN          NaN      

In [9]:
df4 = pd.read_excel(xls, 'Fig 5b',header=None)
tests_indices = [1,22,43]
df_ret_4 = excel_to_df(df4,tests_indices,np.arange(1,35),19,20,diff_col=0)
all_data_df = pd.concat([all_data_df,df_ret_4])
print(len(all_data_df))
print(all_data_df['dpi'].unique())


13419
[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28 90]


In [10]:
df4 = pd.read_excel(xls, 'Fig 5b',header=None)
print(df4.to_string())

        0            1            2             3             4             5             6             7             8             9             10            11            12            13             14            15            16            17            18          19          20          21           22           23           24          25          26           27          28          29          30          31            32          33          34  35                      36                37                38
0   PLASMA          NaN          NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN           NaN           NaN           NaN           NaN         NaN         NaN         NaN          NaN          NaN          NaN         NaN         NaN          NaN         NaN         NaN         NaN         NaN           NaN         NaN         NaN NaN             

In [11]:
def viral_titer_to_df (df1,test_type_indices,num_patients):
    df_ret =  pd.DataFrame(columns = ['patient.number','infected.yn','type.sample','test','value','dpi'])
    for test_index in test_type_indices:
        patient_num = 0
        for index in np.arange(test_index+2,min(test_index+2+num_patients+1,len(df1))):
            patient_num += 1
            for col_num in range(1,38):
                if pd.isna(df1.loc[index,col_num]) == False:
                    try:
                        row_to_add = {'patient.number':[patient_num],
                                    'infected.yn' : ['y'],
                                    'type.sample' : [df1.loc[test_index][0]],
                                    'test': [df1.loc[0][0]],
                                    'value':[df1.loc[index][col_num]],
                                    'dpi':[df1.loc[test_index+1][col_num]]
                                    }
                        df_ret = pd.concat([df_ret,pd.DataFrame(row_to_add)],ignore_index=True)
                    except:
                        continue
    return df_ret
# print(len(pd.read_excel(xls, 'Fig1a',header=None)))
df_ret_5 = viral_titer_to_df(pd.read_excel(xls, 'Fig1a',header=None),[1,22],18)
all_data_df = pd.concat([all_data_df,df_ret_5])
print(all_data_df['dpi'].unique())
print(len(all_data_df))

[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28 90 1.5 2.5 3.5 4.5 5.5 6.5 7.5
 8.5 9.5 10.5 11.5 12.5 13.5 14.5 15.0 15.5 16.0 16.5 17.0 17.5 18.0 18.5
 19.0]
14583


In [12]:
df_ret_6 = viral_titer_to_df(pd.read_excel(xls, 'Fig1b',header=None),[1,22],18)
all_data_df = pd.concat([all_data_df,df_ret_6],ignore_index=True)
print(len(all_data_df))
print(all_data_df['dpi'].unique())

15749
[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28 90 1.5 2.5 3.5 4.5 5.5 6.5 7.5
 8.5 9.5 10.5 11.5 12.5 13.5 14.5 15.0 15.5 16.0 16.5 17.0 17.5 18.0 18.5
 19.0]


In [13]:
import numpy as np
def excel_to_df2 (df1,tests_indices,patients_cols,patients_infected,len_list,sample_type,
                  diff_cols = 2, row_diff = 0):
    all_data_df = pd.DataFrame(columns = ['patient.number','infected.yn','type.sample','test','value','dpi'])
    for test_index in tests_indices:
        test_indices = np.arange(test_index+row_diff,test_index+row_diff+len_list)
        if test_index+row_diff+len_list>len(df1):
            test_indices = np.arange(test_index+row_diff,len(df1))
        for col_num in patients_cols:
            for ind in test_indices:
                if col_num<=patients_infected:
                    infected_yn = 'y'
                else:
                    infected_yn='n'
                row_dict = {'patient.number':[col_num-diff_cols],
                            'infected.yn':[infected_yn],
                            'type.sample':sample_type,
                            'test':[df1.loc[test_index][0]],
                            'value':[df1.loc[ind][col_num]],
                            'dpi':[df1.loc[ind][0]]
                            }
                all_data_df = pd.concat([all_data_df,pd.DataFrame(row_dict)],ignore_index=True)
    all_data_df = all_data_df.dropna()
    return all_data_df

df7 = pd.read_excel(xls, 'Fig S1a',header=None)
df_ret_7 = excel_to_df2(df7,[0,19,38,57,76,95,114,133,152,171,209,228,247,266,285,304,323,342,361,380,399,418,437,456,475,494],
                        patients_cols=np.arange(1,35),patients_infected=19,len_list=18,sample_type='NASAL',
                        diff_cols = 0,row_diff = 1)
all_data_df = pd.concat([all_data_df,df_ret_7],ignore_index=True)
print(len(all_data_df))
print(all_data_df['dpi'].unique())

30725
[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28 90 1.5 2.5 3.5 4.5 5.5 6.5 7.5
 8.5 9.5 10.5 11.5 12.5 13.5 14.5 15.0 15.5 16.0 16.5 17.0 17.5 18.0 18.5
 19.0]


In [14]:
df7 = pd.read_excel(xls, 'Fig S1a',header=None)
print(df7.to_string())

            0            1            2            3            4            5            6            7            8            9             10           11           12           13           14           15           16           17           18           19           20           21           22           23           24           25           26           27           28           29           30           31           32           33           34
0        IL-1a     Infected          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN           NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN   Uninfected          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN
1           -1    61.951148   121.297131   219.498348   194.935944    60.519401    5

In [15]:
df8 = pd.read_excel(xls, 'Fig S1b',header=None)
df_ret_8 = excel_to_df2(df8,[0,18,36,54,72,90,108,126,144,162,180,198,216,234,252,270,288,306,324,342,360,378,396,414,432,],
                        patients_cols=np.arange(2,38),patients_infected=19,len_list=17,sample_type='PLASMA', diff_cols=1,
                        row_diff = 1)
all_data_df = pd.concat([all_data_df,df_ret_8],ignore_index=True)
print(len(all_data_df))
print(all_data_df['patient.number'].unique())

45056
[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36]


In [16]:
print(all_data_df['dpi'].unique())

[-1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 28 90 1.5 2.5 3.5 4.5 5.5 6.5 7.5
 8.5 9.5 10.5 11.5 12.5 13.5 14.5 15.0 15.5 16.0 16.5 17.0 17.5 18.0 18.5
 19.0]


In [16]:
df8 = pd.read_excel(xls, 'Fig S1b',header=None)
print(df8.to_string())

            0     1         2           3           4            5            6            7           8           9           10           11           12           13          14          15          16          17          18          19          20           21          22          23          24          25           26           27          28          29          30          31          32          33          34          35          36          37
0        IL-1a   NaN  Infected         NaN         NaN          NaN          NaN          NaN         NaN         NaN         NaN          NaN          NaN          NaN         NaN         NaN         NaN         NaN         NaN         NaN  Uninfected          NaN         NaN         NaN         NaN         NaN          NaN          NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN
1           -1   NaN  22.86456    7.565607    0.372276     1.332391     0.481834

In [17]:
all_data_df.index = pd.RangeIndex(len(all_data_df.index))
all_data_df
all_data_df.to_csv('all_tests_by_patient.csv',index = False)
